---
steps:
  - label: "Sentence with max 20 characters"
    commands:
      - python -c 'import loremipsum; print(loremipsum.sentence(max_char=20))' > result.txt;
      - printf '%b\n' "$(result.txt)" | buildkite-agent annotate
    agents:
      queue: "mixpix3ls-macbook-air"
    plugins:
      - docker#v5.13.0:
          image: "python:3.13"
          always-pull: true
